### ISSUE TITLE
[CCPA] content selection mechanism

### ISSUE THREAD

**Issue by yoavaviram** [opt-out-eu/yourdigitalrights.org#107]
Design and implement a way for the user to select content. Based on this selection:

- [x] Content on the front page will be changed so that it is relevant to both legislation
- [x] User selects legislation on the Send Request form
- [x] Different email templates should be rendered based on the selection

Design for the form: https://app.zeplin.io/project/5b07cf7b9af8b1243f584d16/screen/5d1f7827fecc97298170d70f

**Comment by roughprada** [comment]
@yoavaviram can we call this done?

**Comment by yoavaviram** [comment]
Yes
