### ISSUE TITLE
[Thank You] social module offset broken on thank you page

### ISSUE THREAD

**Issue by roughprada** [opt-out-eu/yourdigitalrights.org#119]
Broken thank you page:

<img width="1502" alt="Screenshot 2019-11-19 at 07 20 05" src="https://user-images.githubusercontent.com/5957010/69125145-0e0b8280-0a9d-11ea-931c-2168c8623de0.png">

Original Design:

![thank you copy 2](https://user-images.githubusercontent.com/5957010/69125200-2da2ab00-0a9d-11ea-98d0-8685934c3463.png)

**Comment by yoavaviram** [comment]
@roughprada is anyone working on this?

**Comment by yoavaviram** [comment]
@roughprada ?

**Comment by roughprada** [comment]
@yoavaviram This one has not being picked up yet

**Comment by yoavaviram** [comment]
Fixed
