### ISSUE TITLE
Bablic not showing visual editor

### ISSUE THREAD

**Issue by roughprada** [opt-out-eu/yourdigitalrights.org#127]
When I go to Bablic to translate to Spanish, the only copy that I can see is the old Opt Out one and when I go to visual editor, the tool says that we don't have the snippet installed

<img width="1552" alt="Screenshot 2019-12-17 at 07 15 42" src="https://user-images.githubusercontent.com/5957010/70973360-739f5e80-209d-11ea-9caf-ef8b52227574.png">

**Comment by roughprada** [comment]
@roughprada can you have a look at this? I can't see why this is not working well.

**Comment by yoavaviram** [comment]
Try now.

**Comment by roughprada** [comment]
yes, thanks!
