### ISSUE TITLE
[default mail reader] email not showing - BRAVE

### ISSUE THREAD

**Issue by roughprada** [opt-out-eu/yourdigitalrights.org#129]
When I have my default mail reader as Brave, the template doesn't appear

**Comment by roughprada** [comment]
@yoavaviram this is a bit worrying?

**Comment by yoavaviram** [comment]
Works on mine, but it asked for permission to open chrome (which is defined as my default email client). If you ever said no then it will not open.

**Comment by roughprada** [comment]
nope, not working for me. I am just concerned as Brave is becoming really popular.

**Comment by roughprada** [comment]
@yoavaviram we are also receiving requests as users are having issues with the mailto, I'll pass it into Slack and see.

**Comment by yoavaviram** [comment]
@roughprada what is your default email client?

**Comment by roughprada** [comment]
Yes

**Comment by roughprada** [comment]
@yoavaviram sorry, I read it wrong. My default browser and mail client is Brave

**Comment by yoavaviram** [comment]
What happens when you click [this](mailto:yoav@opt-out.eu)?

**Comment by roughprada** [comment]
nothing happens :(

**Comment by yoavaviram** [comment]
Then it's a problem with your configuration, not with our website... The link above works with a clean installation of Brave.

**Comment by roughprada** [comment]
I'll re install, but this is happening on a fresh installation of brave.

>

**Comment by yoavaviram** [comment]
When you first use it, watch out for permission messages

**Comment by roughprada** [comment]
Still not working :/

**Comment by yoavaviram** [comment]
Not sure what to say except it's a bigger problem for you then our website. I suggest closing this issue.
