### ISSUE TITLE
[Thank You] Social sharing buttons are not shown

### ISSUE THREAD

**Issue by yoavaviram** [opt-out-eu/yourdigitalrights.org#68]
Social sharing buttons are not shown in my browser because of an ad blocker. What did you use to implement this? Is it a library or home grown? If it’s home grown then we can easily circumvent the ad blocker rule by changing the names and URLs of the icons (ie ’/share/facebook*’).

**Comment by roughprada** [comment]
@yoavaviram is this still the case?

**Comment by yoavaviram** [comment]
Yes, would be great to fix this

**Comment by yoavaviram** [comment]
ublock origin on Chrome / FF

**Comment by roughprada** [comment]
Is that a specific configuration? I have ublock origin and I can't replicate the issue

**Comment by yoavaviram** [comment]
Make sure you are looking at the thank you page. I had no problems with the homepage.

**Comment by roughprada** [comment]
Still, all good my end. I've checked Firefox users on Matomo, but I can't
find out if they use ublock. So far, everyone that get's to the thank you
page can see the icons.

**Comment by yoavaviram** [comment]
How are you checking on Matomo?

**Comment by roughprada** [comment]
@yoavaviram is this finished too?
